### ISSUE TITLE
Missing files prevent compilation

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [lewish/asciiflow2#98]
I attempted to follow the instructions in the README file to run asciiflow locally. This led to a sequence of errors.

Error 1
=====
Invoked: `./compile.sh` and got the following in response:

```
WARNING - Failed to load module "./boxtext.js"

js-lib/draw/index.js:3: ERROR - required "module$js_lib$draw$boxtext" namespace never provided
export { default as DrawBoxText } from './boxtext';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

See the line in question here:
https://github.com/lewish/asciiflow2/blob/master/js-lib/draw/index.js#L3

A quick search reveals that *that* line is the only reference to `DrawBoxText` in the repo. So, I eliminate the line which brings us to the next problem.

Error 2
=====

```
js-lib/controller.js:38: WARNING - Bad type annotation. Unknown type DrawFunction$$module$js_lib$draw$index
    /** @type {DrawFunction} */ this.drawFunction = new DrawBox(state);
               ^
```

I know literally nothing about javascript and can't determine why *this* is a problem. It's certainly imported (e.g., https://github.com/SeanCurtis-TRI/asciiflow2/blob/master/js-lib/controller.js#L6). However, by removing the documentation, things proceed nicely.

**Comment by AWolf81** [comment]
# Error 1 
Yes, I've also commented `boxtext` export to be able to compile. Not sure why it is there but should be OK to be removed.

# Error 2 
It's just a warning but it can be fixed by directly importing `import DrawFunction from './draw/function';` instead of the re-exporting from `./draw/index`. Not sure if there is a better solution but it's a working work-around. 
It's also mentioned at this [issue](https://github.com/google/closure-compiler/issues/1721).

**Comment by Qix-** [comment]
Hi there. I know this is super old, but it doesn't appear to be an issue anymore.

Going to optimistically close this for now - let me know if it's still a problem.
